# Machine Support

snd-soc-smdks5p-wm8580-objs  := smdks5p_wm8580.o

obj-$(CONFIG_SND_S3C_I2S_V50)  += s3c-pcm-lp.o
obj-$(CONFIG_SND_S3C_I2S_V50)  += s3c-i2s.o

obj-$(CONFIG_SND_SMDKC100_WM8580)  += snd-soc-smdks5p-wm8580.o
obj-$(CONFIG_SND_SMDKC110_WM8580)  += snd-soc-smdks5p-wm8580.o
obj-$(CONFIG_SND_SMDK6442_WM8580)  += snd-soc-smdks5p-wm8580.o
