obj-$(CONFIG_VIDEO_FIMC2)	+= fimc_core.o fimc_v4l2.o fimc_capture.o fimc_output.o fimc_overlay.o fimc_cfg.o
obj-$(CONFIG_VIDEO_FIMC_MIPI)	+= csis.o
obj-$(CONFIG_ARCH_S5PC1XX)	+= fimc4x_regs.o
obj-$(CONFIG_S5K3BA)		+= s5k3ba.o
obj-$(CONFIG_S5K4BA)		+= s5k4ba.o

EXTRA_CFLAGS += -Idrivers/media/video

