#################################################
# Makefile for Image Rotator 
# 2009 (C) Samsung Electronics 
# Author : Jonghun Han <jonghun.han@samsung.com>
#################################################

obj-$(CONFIG_CPU_S5PC100)	+= s3c_rotator.o
obj-$(CONFIG_CPU_S5PC110)	+= s3c_rotator.o
obj-$(CONFIG_CPU_S5P6442)	+= s3c_rotator2.o

EXTRA_CFLAGS += -Idrivers/media/video

